version: '3'

services:
  postgres:
    image: 'postgres:15-alpine'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: videodb-user
      POSTGRES_DB: videodb
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - cluster

volumes:
  postgres:


secrets:
  db_password:
    file: ./secrets/POSTGRES_PASSWORD

networks:
  cluster:
    driver: bridge
