version: '3'

services:
  db_server:
    image: 'postgres:15-alpine'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: videodb-user
      POSTGRES_DB: videodb
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - front
  app:
    image: 'camg-solution:latest'
    volumes:
      - ./data:/app/data
      - ./secrets:/app/secrets
    networks:
      - front

volumes:
  postgres:

secrets:
  db_password:
    file: ./secrets/POSTGRES_PASSWORD

networks:
  front:
    driver: bridge
